### PR TITLE
fix (output/modifiers): unescape characteres of output html

### PR DESCRIPTION
**Pull request by dogatana**
Non-ASCII charcters of  output html files are escaped.
This PR do replace all `&#x<4 hex diigits>;` to unescaped charctares.
As a result, this PR requires update of snapshot.

Close Issue #87

### CODE REVIEW

**Comment by azu** [comment]
Thanks for PR!

Probably, we can use `decodeEntities` option of cheerio instead of it.
(I've not tested yet)

Can you try it?

- [$.html() encoding apostrophes · Issue #319 · cheeriojs/cheerio](https://github.com/cheeriojs/cheerio/issues/319)
- [cheerio | Fast, flexible, and lean implementation of core jQuery designed specifically for the server.](https://cheerio.js.org/)
- [Parser options · fb55/htmlparser2 Wiki](https://github.com/fb55/htmlparser2/wiki/Parser-options)

Also, I want to add some test cases for this PR like `__snapshots__/decodeEntities.md`
This fixtures will includes some text.

```
"Hello"
"こんにちは"
"한글"
"你好"
"先生"
"👋"
```

inspired by https://github.com/microsoft/vscode/wiki/IME-Test#test

**Comment by dogatana** [comment]
> robably, we can use decodeEntities option of cheerio instead of it.

I've already tried decodeEntities option but could not get a good result.

The reason is that
- modifyHTML uses cheerio module
- cheerio.html can accept decodeEntities option
- cheerio.html simply pass the option to entities
- entities use it to encode characters like '<' __AND__ non-ASCII characters

It seems to be hard to change cheerio and/or entities in order to solve the issue.
I think a kind of post-process is good enough.

What do you think?

**Comment by dogatana** [comment]
I'm considering expandinng code range from 4 hex-digits to 2 and more digits, `&#x[0-9a-f]{2,};`
With this, we can create the following book.

```html
<table>
<thead>
<tr> <th>Category</th> <th>Text</th> </tr>
</thead>
<tbody> <tr> <td>Japanese</td> <td>こんにちは</td> </tr>
<tr> <td>Chinese(Simplified)</td> <td>你好</td> </tr> 
<tr> <td>Portuguese</td> <td>olá</td> </tr>
<tr> <td>Russin</td> <td>приветствие</td> </tr> 
<tr> <td>Korean</td> <td>안녕하세요</td> </tr> 
<tr> <td>Emoji (<code>u+1f91d</code>)</td> <td>🤝</td> </tr>
</tbody>
</table>
 ```
image

**Comment by azu** [comment]
I see.
I'm ok current implementation.
I have concerned that encoding/decoding is duplicated in the process.

**Comment by dogatana** [comment]
> I have concerned that encoding/decoding is duplicated in the process.

True.
But this happens only when building book, and I can accept it to avoid annoying encoding.

**Review by azu — APPROVED** [review]
LGTM
Thanks!

**Pull request merged**
