### PR TITLE
pref(tsconfig.json) : change typescript configuration

### PR DESCRIPTION
**Pull request by harshilparmar**
- Made changes in compilerOptions targeted javascript

Issue reference: #66

### CODE REVIEW

**Comment by HugoDF** [comment]
@harshilparmar have you checked that everything works on Node 10? It might be worth adding Node 10 to the test matrix for GitHub Actions (if only temporarily for this PR) cc @azu

**Comment by harshilparmar** [comment]
> 
> 
> @harshilparmar have you checked that everything works on Node 10? It might be worth adding Node 10 to the test matrix for GitHub Actions (if only temporarily for this PR) cc @azu
Sorry I didn't check everything @HugoDF

**Comment by HugoDF** [comment]
Sorry I didn't mean it literally, have you checked that the tests pass on Node 10?

**Comment by harshilparmar** [comment]
> 
> 
> Sorry I didn't mean it literally, have you checked that the tests pass on Node 10?
Noting to worry about that. 
Yes, it passes all tests. I checked with the `yarn test` it passed all tests. Please correct me If I am wrong.

**Comment by harshilparmar** [comment]
@HugoDF For that, I have to downgrade my node version? Or It was correct ? Correct me I am wrong.

**Comment by HugoDF** [comment]
> @HugoDF For that, I have to downgrade my node version? Or It was correct ? Correct me I am wrong.

Yeah if you downgrade to Node 10 and the tests pass then we're good

Up to @azu if he wants to run Node 10 on the automated test suite (since we support Node 10 if makes sense to I think but not my call)

**Comment by harshilparmar** [comment]
@HugoDF Yes its working fine on node version v10.18.0

**Comment by azu** [comment]
Thanks!

>  It might be worth adding Node 10 to the test matrix for GitHub Actions (if only temporarily for this PR

Yeah! It is reasonable.

**Comment by azu** [comment]
@HugoDF Thanks to review 👍 
I want to invite you HonKit organization!
I've submit invitation 📥

**Pull request merged**
